"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-01-01

This bootstrap migration materialises the full v1 schema directly from the
SQLAlchemy models (single source of truth). Subsequent schema changes should
use autogenerated migrations:

    alembic revision --autogenerate -m "describe change"
"""
from typing import Sequence, Union

from alembic import op

from app.db.base import Base
import app.models  # noqa: F401

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
